### PR TITLE
Fix riemann output plugin

### PR DESCRIPTION
**Pull request by jhitze**
So, I added some tests. Fixed the event -> hash problem ( #2 and #3 ). Refactored a few others. I'm not great with rspec, but I hope this is good enough. Let me know if is anything you want me to fix.

### CODE REVIEW

**Comment by jamtur01** [comment]
Awesome to see this fixed. @jhitze I think you need to sign the Logstash CLA though - https://www.elastic.co/contributor-agreement

**Comment by suyograo** [comment]
@jhitze thanks! yes, please sign the CLA and we can get this merged

**Comment by jhitze** [comment]
I did sign the CLA when I pushed a fix for a different plugin.

**Comment by jamtur01** [comment]
@jhitze Same email address?
@suyograo Looks like an issue with your CLA verification perhaps?

**Comment by jhitze** [comment]
I've filled out two, for purduefed and one for gmail.

**Comment by suyograo** [comment]
CLA check is ok

**Comment by sonnysideup** [comment]
Let's merge it!

**Comment by jordansissel** [comment]
@drywheat and @jamtur01 think this is ready for merging. +1 to go ahead.

**Comment by suyograo** [comment]
@jhitze 0.2.0 has been published. Thanks for the PR! <3

**Pull request closed without merging**
