### PR TITLE
Fix crash in map_fields and fix riemann_event for "%{field}" strings

### PR DESCRIPTION
**Pull request by venturaville**

### CODE REVIEW

**Comment by jordansissel** [comment]
Prior conversations here: https://github.com/elasticsearch/logstash-contrib/pull/136

**Comment by venturaville** [comment]
I can add an explanation of what broke versus not, but I am not sure where plugin doc updates go...

**Comment by jordansissel** [comment]
ahh I should have been more clear, sorry!

Doc updates - docs live inside the plugin itself. The comments above the 'config' lines become the docs for that config setting. The comments above the class definition for the plugin become the description/etc of the plugin in its documentation.

**Comment by venturaville** [comment]
per you request, this problem is to address a conflict between map_fields and riemann_event.  riemann_event wants to be able to map fields using "%{fieldName}" similar to what other modules do.  map_fields does not use the sprintf from the event which allows for that and instead just blindly writes things out which results in the raw "%{fieldName}" showing up in the results instead of the substituted field.

**Comment by hmrm** [comment]
@jordansissel @venturaville Anything in the way of getting this merged?

**Comment by corradio** [comment]
Heavily interested in this! Let me know if I can help!

**Comment by adnan-panalytics** [comment]
@jordansissel @ph Is there any reason why this fix has not been merged? Need to update our logstash config, and this merge is vital to it.

**Comment by jamtur01** [comment]
Any chance of movement on this? It's blocking a deployment for us too. Happy to patch locally but would prefer upstream.

**Comment by jsvd** [comment]
@venturaville since you signed the cla with a different email than the one [in this pr](https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-output-riemann/pull/1.patch) would you mind force pushing it again with the cla email so we can merge this?

**Comment by jamtur01** [comment]
@venturaville Any chance of a new push? If not - would you be cool if someone took over the patch and submitted it? Thanks!

**Comment by venturaville** [comment]
I signed the CLA with my venturaville account.  Should be good now.

**Comment by jamtur01** [comment]
@venturaville Awesome - thanks so much! 

@jordansissel All yours! :)

**Comment by venturaville** [comment]
Any suggestions on how to do a force push?   It looks as though github was picking up my non-personal key and ignoring my personal one.

**Comment by jamtur01** [comment]
`git push --force` not working?

**Comment by jamtur01** [comment]
@venturaville Can I help with a push in some way?

**Pull request closed without merging**
